name: Build APK

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build release APK
        run: ./gradlew clean assembleRelease
