name: Build APK

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build release APK
        run: ./gradlew clean assembleRelease
