name: Lint code

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run lint checks
        run: ./gradlew clean lint

      - name: Run ktlint checks
        run: ./gradlew clean ktlintCheck
